server:
  port: 9091

spring:
  application:
    name: gateway-serer
  cloud:
    gateway:
      routes:
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/api/v1/user/**
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

