twilio:
  account_sid: ${SID}
  auth_token: ${TOKEN}
  service_id: ${ID}


server:
  port: 9093

spring:
  application:
    name: auth
jwt:
  secret: secretkey
  token:
    validity: 3600_000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
